### ISSUE TITLE
Default value of undefined for nextState in ActionState constructor should be removed

### ISSUE THREAD

**Issue by jthpotz** [panoptyk/example-game#5]
There shouldn't be a default value of undefined for the nextState in the ActionState constructor. If we are going with the convention of passing in the nextState functions, it will help cut down on errors. It would warn you that you are missing the transition function instead of causing an error at runtime when tick tries to call nextState and it is undefined.

**Comment by scm2217** [comment]
Passing in the nextState is meant to be optional, a default nextState should be defined for every action. We should have a group discussion on how we are handling transitions.

**Comment by mitchkm** [comment]
I think this ties in with issue #3. The reason nextState is an optional parameter to pass into the constructor is because nextState() is abstract. This means you must define a default one when you extend the class. This goes back to how you may just be fine defining the transitions right there and now. 

Also if you do have a state that requires a nextState you can override the previous constructor to require it as a param.
